# -*- coding: utf-8 -*-
"""json_automatizao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8ujokjp3Lw3Hrhl8Orx_rcLOJSNcjBy
"""

import pandas as pd

predictions = pd.read_csv('https://challenges-asset-files.s3.us-east-2.amazonaws.com/data_sets/Data-Science/4+-+events/itacademy/pre-hack-challenge/ground_truth.csv')

predictions = predictions.to_json(orient='values')

"""[to_json](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html//)"""

predictions

from google.colab import files

files.download()

import pandas as pd

predictions = pd.read_csv('https://challenges-asset-files.s3.us-east-2.amazonaws.com/data_sets/Data-Science/4+-+events/itacademy/pre-hack-challenge/ground_truth.csv')

prediction_caixa = pd.read_csv("https://challenges-asset-files.s3.us-east-2.amazonaws.com/data_sets/Data-Science/4+-+events/CaixaBankTech/predictions.csv")

predictions = predictions.to_json()
prediction_caixa = prediction_caixa.to_json()

predictions

prediction_caixa
